### PR TITLE
Unrolling stones

### PR DESCRIPTION
**Pull request by stp59**
I am mostly just opening this PR so that I have something to link my project report to tonight. However, it is ready for some review! There a few outstanding issues that need to be resolved, but the main part of the tool is working! More details on these issues coming soon...

### CODE REVIEW

**Comment by rudynicolop** [comment]
Looks good!

**Comment by hackedy** [comment]
Sorry for not looking at this yet. Should I read through and try to merge or are we just going to use your Coq port instead?

**Comment by hackedy** [comment]
Can we close this and delete the branch?

**Comment by stp59** [comment]
I think so! I just had to open a PR because this was a class project lol. Although the code doesn't live anywhere else...

**Comment by hackedy** [comment]
Let's take the 1 file from this branch and the cli/frontend changes and put them on main.

**Pull request closed without merging**
