### PR TITLE
Unify fresh name generators using Iris stdpp

### PR DESCRIPTION
**Pull request by hackedy**
This pull request turns several fresh name generators into one fresh name generator that relies on an efficient implementation of finite maps and name-freshening found in the Iris stdpp library.

### CODE REVIEW

**Comment by hackedy** [comment]
I can't reproduce the CI build failure locally....

**Comment by hackedy** [comment]
I think the problem here is that Iris modules are named in lower case (so, `stdpp.stringmap` not `stdpp.Stringmap`) and this is no problem on a case insensitive file system  like my laptop. But on an actual case sensitive filesystem it breaks the dune extracted_modules check somehow.

**Comment by hackedy** [comment]
Fixed CI, ready for review!

**Comment by rudynicolop** [comment]
Should this be merged before or after #434?

**Review by rudynicolop — APPROVED** [review]

**Comment by hackedy** [comment]
> Should this be merged before or after #434?

Merge #434 first and I can adjust this PR to deal with any conflicts.

**Comment by hackedy** [comment]
Turns out the PRs are totally independent because P4cub doesn't need fresh name generation anywhere (due to de Bruijn) 👍

**Pull request merged**
