### PR TITLE
Functor Notations

### PR DESCRIPTION
**Pull request by zachary0kent**
Adds an infix operators for (applicative) functors

### CODE REVIEW

**Comment by hackedy** [comment]
Do you want to add an applicative typeclass, or is it just for monad operations?

**Comment by zachary0kent** [comment]
> Do you want to add an applicative typeclass, or is it just for monad operations?

Do you think it would be worth adding an applicative typeclass? Also, do you know if there's a reason we rolled our monads instead of using the definitions in say `coq-ext-lib`?

**Comment by hackedy** [comment]
I think a standalone Applicative typeclass is probably not worth it.

My impression was that ext-lib doesn't provide that much beyond what we have. I'd be interested in using stdpp or something like that though.

**Comment by zachary0kent** [comment]
> I think a standalone Applicative typeclass is probably not worth it.
> 
> My impression was that ext-lib doesn't provide that much beyond what we have. I'd be interested in using stdpp or something like that though.

Makes sense. Do you think this is good to merge then?

**Pull request merged**
