### PR TITLE
Make the main branch compatible with Coq 8.16.1

### PR DESCRIPTION
**Pull request by txyyss**
Some automation does not work for Coq 8.16. I fixed one but still have to leave some manual proof. If any of you have time, we can have a Zoom meeting to discuss how to improve the current fix.

I only test the code on Coq 8.16.1. It may break on Coq 8.15.

### CODE REVIEW

**Comment by hackedy** [comment]
Looks like CI is failing because it runs it on Coq 8.15. Should we just require 8.16 in the dune-project file? (The opam file is generated by Dune from the dependencies in the dune-project file so it shouldn't be edited manually)

**Comment by hackedy** [comment]
Yeah CI is using 8.15.2 https://github.com/verified-network-toolchain/petr4/actions/runs/5466619661/jobs/9951808416#step:5:69

**Comment by txyyss** [comment]
> Yeah CI is using 8.15.2 https://github.com/verified-network-toolchain/petr4/actions/runs/5466619661/jobs/9951808416#step:5:69

Should I configure the CI of this branch to make it work first? or should I tweak the proof script to make it compatible for both 8.15 and 8.16.

**Comment by hackedy** [comment]
> Should I configure the CI of this branch to make it work first? or should I tweak the proof script to make it compatible for both 8.15 and 8.16.

Proof script tweaks would be less disruptive but if it ends up being too complicated to fix an upgrade would be fine with me.

**Comment by txyyss** [comment]
> > Should I configure the CI of this branch to make it work first? or should I tweak the proof script to make it compatible for both 8.15 and 8.16.
> 
> Proof script tweaks would be less disruptive but if it ends up being too complicated to fix an upgrade would be fine with me.

Some of my upgrade fix is ad hoc when automatic tactics failed. For example, the CI failed with `Error: No such goal.` because on 8.16 the tactic would leave an unsolved goal while on 8.15 it would not. Since I'm not familiar with existing proof I can not figure out which trial failed on 8.16. So if you have time this week or future, I would like to have a Zoom meeting with you to discuss how to fix it in a better way, without breaking the automation. Thank you very much.

**Review by hackedy — APPROVED** [review]

**Pull request merged**
